github: [krishnazzz, s8ulkrishna2006-stack]
patreon: your-username
ko_fi: your-username
buy_me_a_coffee: your-username
custom: ["https://www.paypal.me/yourusername", "https://yourwebsite.com/donate"]
